---
# search role tasks
- name: RedHat | Install Elasticsearch Yum repo
  template: src={{ ansible_os_family }}/elasticsearch.repo
            dest=/etc/yum.repos.d/
            mode=0644

- name: RedHat | Install Elastic RPM key
  rpm_key: state=present
           key=https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: RedHat | Install elasticsearch dependencies
  yum: name={{ item }}
       state=present
  with_items: elasticsearch_dependencies

- name: RedHat | Install elasticsearch
  yum: name="elasticsearch-{{ elasticsearch_version }}"
       state=present

- name: RedHat | Ensure elasticsearch is running automatically at boot time
  action: command chkconfig --add elasticsearch
