---
- name: Debian | Install Elastic RPM key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch
           state=present

- name: Debian | Install Elasticsearch Deb repo
  copy: content="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"
        dest=/etc/apt/sources.list.d/elasticsearch.list

- name: Debian | Install elasticsearch dependencies
  apt: name={{ item }}
       state=present
       update_cache=yes
  with_items: elasticsearch_dependencies

- name: Debian | Install elasticsearch
  apt: name="elasticsearch={{ elasticsearch_version }}"
       state=present
       update_cache=yes

- name: Debian | Check if elasticsearch service will start at boot time
  command: ls /etc/rc*.d | grep 'elasticsearch'
  register: elasticsearch_registered

- name: Debian | Ensure elasticsearch is running automatically at boot time
  command: update-rc.d elasticsearch defaults 95 10
  when: elasticsearch_registered == false
