---
# search role tasks
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - elasticsearch
    - always

- include: install.yml
  tags:
    - elasticsearch
    - install

- include: configure.yml
  tags:
    - elasticsearch
    - configure
